name: UAMP Build with MPLAB X and XC8
description: This action builds a MPLAB X / XC8 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.20"
  xc8_version:
    description: Version of the XC8 compiler to use
    required: true
    default: "2.50"
  dfp_packs:
    description: DFP packs to install
    required: false
    default: "ATtiny_DFP=3.2.268"
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
runs:
  using: docker
  image: Dockerfile
  env:
    MPLABX_VERSION: ${{ inputs.mplabx_version }}
    XC8_VERSION: ${{ inputs.xc8_version }}
    DFP_PACKS: ${{ inputs.dfp_packs }}
    PROJECT: ${{ inputs.project }}
    CONFIGURATION: ${{ inputs.configuration }}
    JAVA_OPTS: "-Xmx4G"

