name: UAMP Build with MPLAB X and XC8
description: This action builds a MPLAB X / XC8 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.20"
  xc8_version:
    description: Version of the XC8 compiler to use
    required: true
    default: "2.50"
  dfp_packs:
    description: DFP packs to install
    required: false
    default: "ATtiny_DFP=3.1.260"
runs:
  using: docker
  image: Dockerfile
  build-args: |
    mplabx_version=${{ inputs.mplabx_version }}
    xc8_version=${{ inputs.xc8_version }}
    dfp_packs=${{ inputs.dfp_packs }}
    project=${{ inputs.project }}
    configuration=${{ inputs.configuration }}
